/**
 * Rotating verbs for the Working row.
 *
 * Curated in-repo so the list stays original, short, and single-line; each
 * entry is a present participle that reads as "X..." while the agent runs.
 */

/**
 * The built-in verb list, grouped by theme.
 *
 * Kept at exactly 200 entries; `working-verbs.test.ts` enforces the count,
 * uniqueness, width, and shape so the list cannot drift silently.
 */
export const WORKING_VERBS: readonly string[] = [
    // Kitchen
    "Brewing",
    "Simmering",
    "Saut\u00e9ing",
    "Caramelizing",
    "Whisking",
    "Kneading",
    "Proofing",
    "Marinating",
    "Brining",
    "Zesting",
    "Julienning",
    "Fermenting",
    "Tempering",
    "Emulsifying",
    "Flavouring",
    "Drizzling",
    "Glazing",
    "Steeping",
    "Blanching",
    "Basting",
    "Curing",
    "Infusing",
    "Decanting",
    "Frothing",
    "Folding",
    "Sifting",
    "Scalding",
    "Rendering",
    "Braising",
    "Poaching",
    // Growth and nature
    "Germinating",
    "Sprouting",
    "Budding",
    "Composting",
    "Fruiting",
    "Rooting",
    "Grafting",
    "Trellising",
    "Sowing",
    "Mulching",
    "Pruning",
    "Blooming",
    "Leafing",
    "Photosynthesizing",
    // Water and weather
    "Billowing",
    "Drifting",
    "Rippling",
    "Sleeting",
    "Thawing",
    "Condensing",
    "Evaporating",
    "Welling",
    "Cresting",
    "Eddying",
    "Braiding",
    "Wending",
    "Pooling",
    "Drumming",
    "Pattering",
    "Crystallizing",
    // Sky and space
    "Dawning",
    "Kindling",
    "Smouldering",
    "Glimmering",
    "Shimmering",
    "Coruscating",
    "Alighting",
    "Blazing",
    "Constellating",
    "Telescoping",
    "Redshifting",
    "Warping",
    "Reentering",
    "Spacewalking",
    "Orbiting",
    "Slingshotting",
    "Eclipsing",
    "Waxing",
    "Transiting",
    "Occulting",
    // Workshop and craft
    "Chiselling",
    "Sanding",
    "Planing",
    "Joining",
    "Dovetailing",
    "Mortising",
    "Turning",
    "Annealing",
    "Forging",
    "Soldering",
    "Welding",
    "Riveting",
    "Casting",
    "Firing",
    "Enamelling",
    "Inlaying",
    "Stitching",
    "Splicing",
    "Lashing",
    "Fletching",
    "Furling",
    "Caulking",
    "Plastering",
    "Trowelling",
    "Levelling",
    // Code and dev life
    "Refactoring",
    "Debugging",
    "Compiling",
    "Bundling",
    "Hashing",
    "Minifying",
    "Bisecting",
    "Rebasing",
    "Merging",
    "Reverting",
    "Stubbing",
    "Mocking",
    "Linting",
    "Formatting",
    "Serializing",
    "Deserializing",
    "Throttling",
    "Debouncing",
    "Memoizing",
    "Currying",
    "Inlining",
    "Pipelining",
    "Sharding",
    "Queuing",
    "Streaming",
    "Caching",
    // Science and lab
    "Titrating",
    "Pipetting",
    "Centrifuging",
    "Catalyzing",
    "Dissolving",
    "Saturating",
    "Diluting",
    "Assaying",
    "Sequencing",
    "Cloning",
    "Culturing",
    "Staining",
    "Sectioning",
    "Etching",
    "Sputtering",
    "Recrystallizing",
    "Morphing",
    "Lasing",
    "Tunnelling",
    "Entangling",
    "Decohering",
    "Supercooling",
    "Quenching",
    // Music and movement
    "Tuning",
    "Strumming",
    "Plucking",
    "Bowing",
    "Trilling",
    "Arpeggiating",
    "Syncopating",
    "Stomping",
    "Tapping",
    "Crooning",
    "Humming",
    "Whistling",
    "Rehearsing",
    "Conducting",
    "Arranging",
    "Modulating",
    "Resonating",
    "Waltzing",
    "Sashaying",
    "Swinging",
    // Journeys
    "Trekking",
    "Trundling",
    "Portaging",
    "Skating",
    "Glissading",
    "Switchbacking",
    "Bushwhacking",
    "Snowshoeing",
    "Paddling",
    "Sculling",
    "Tacking",
    "Anchoring",
    "Docking",
    "Coasting",
    // Whimsy
    "Kerfuffling",
    "Confabulating",
    "Chortling",
    "Galumphing",
    "Whooshing",
    "Zipping",
    "Bouncing",
    "Wobbling",
    "Twirling",
    "Pirouetting",
    "Cartwheeling",
    "Wriggling",
];

/**
 * Pick a verb from `verbs` using `rng` (defaults to `Math.random`).
 *
 * Returns `undefined` for an empty list so callers can fall back to their
 * default label; seeded `rng` values make the choice deterministic in tests.
 */
export function pickWorkingVerb(
    verbs: readonly string[],
    rng: () => number = Math.random,
): string | undefined {
    if (verbs.length === 0) return undefined;
    const index = Math.min(verbs.length - 1, Math.floor(rng() * verbs.length));
    return verbs[index];
}
